repos:
  - repo: local
    hooks:
      # - id: cargo-audit
      #   name: cargo audit
      #   entry: cargo audit
      #   language: system
      #   pass_filenames: false

      - id: cargo-click
        name: cargo click
        entry: cargo clippy --
        language: system
        pass_filenames: false

      - id: cargo-test-all-features
        name: cargo test all-features
        entry: cargo test --release --all-features
        language: system
        pass_filenames: false

      - id: cargo-test-no-features
        name: cargo test no features
        entry: cargo test --release
        language: system
        pass_filenames: false
