name: Rust Code

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-rust-toolchain-for-github-ci
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo install cargo-audit

      - run: cargo audit

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/pre-commit
      - uses: pre-commit/action@v3.0.1
